CHANGELOG.md, Gemfile.lock, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb
This is converting from a statically defined list for ignorable tables to use the Rails APIs in order to get the configured metadata tables.
Note: `schema_info` was removed because it is the table that Rails used instead of `schema_migrations` as the default `schema_migrations_table_name` pre Rails 3.  Because (1) this gem does not support anything pre Rails 4, and (2) any projects that are still using `schema_info` instead of `schema_migrations` for the schema migration table should be setting the `schema_migrations_table_name` attribute in their Rails configuration, this static declaration has been removed.
=> TECH-4876: use rails apis for getting internal metadata table names

CHANGELOG.md, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/generators/declare_schema/migration/migrator_spec.rb
Fixes 2 bugs from TECH-4970:
1. The `:text limit:` was being omitted if it was the max, 0xffff_ffff. This was a bug because I misunderstood and thought that was the Rails default size. Actually, the Rails default matches the MySQL default, which is `0xffff`. The fix always emits the `limit:` since it's harmless to be explicit, just like we do with `:string limit: 255`.
2. The `:integer limit: 8` change that Alec added for foreign keys was actually broken in `declare_schema` because it was being overwritten. This is fixed here. Note that we still have a bit of a problem generating these migrations in that Rails 5 will consider the columns type `:bigint` whereas `declare_schema` calls them `:integer limit: 8` and doesn't know these are equivalent. So I think it will forever try to migrate …
=> TECH-4970: never omit text limit

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model.rb, lib/declare_schema/version.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/declare_schema/prepare_testapp.rb
- Added support for `belongs_to optional:`.
If given, it is passed through to `ActiveRecord`'s `belong_to`.
If not given in Rails 5+, the `optional:` value is set equal to the `null:` value (default: `false`) and that is passed to `ActiveRecord`'s `belong_to`.
Similarly, if `null:` is not given, it is inferred from `optional:`.
If both are given, their values are respected, even if contradictory; this is a legitimate case when migrating to/from an optional association.
=> STORY-8887: add support for belongs_to optional:

CHANGELOG.md, Gemfile.lock, README.md, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/generators/declare_schema/migration/migrator_spec.rb
- Added a new callback `before_generating_migrations` to the `Migrator` that can be
defined in order to custom load more models that might be missed by `eager_load!`
The following configuration options are available for the gem and can be used
during the initialization of your Rails application.
During the initializtion process for generating migrations, `DeclareSchema` will
trigger the `eager_load!` on the `Rails` application and all `Rails::Engine`s loaded
into scope.  This sometimes won't load all the necessary models for generating
migrations against, so we've introduced a callback that when defined is executed just
after this eager loading process.
**Example Configuration**
```ruby
DeclareSchema::Migration::Migrator.before_generating_migrations do
require 'lib/some/hidden/models.rb' …
```
=> Tech 4972 create callback for loading other models

spec/lib/declare_schema/api_spec.rb, spec/lib/declare_schema/generator_spec.rb, spec/lib/declare_schema/interactive_primary_key_spec.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/spec_helper.rb, spec/support/acceptance_spec_helpers.rb
This is the pre-review PR for the new helpers that are being added for running acceptance tests in the gem. These should help with readability and understandability of the code that is doing the tests.
The following helpers have been added so far with:
1. `generate_model` acts as a shorthand for running the command line generator method for `declare_schema:model`
2. `generate_migrations` acts as a shorthand for executing the command line generator `declare_schema:migration`
3. `clean_up_model` cleans up the necessary generated files for a given model
4. `expect_model_definition_to_eq` is a slim helper to help with comparing generated model files with the expected generated  source
5. `expect_test_definition_to_eq` is a slim helper to help with comparing generated model test files with the …
=> Tech 4937 create test dsl for acceptance tests

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/migration_generator_spec.rb
Fixes TECH-5016
- When passing `belongs_to` to Rails, suppress `optional:` option in Rails 4, since it predates the introduction of that option.
=> TECH-5016: suppress belongs_to optional: in rails4

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model.rb, lib/declare_schema/version.rb, spec/lib/declare_schema/migration_generator_spec.rb
TECH-4995
- Fields may be declared with `serialize: true` or `serialize: <serializeable-class>`, where `<serializeable-class>` 
may be `Array` (`Array` stored as YAML) or `Hash` (`Hash` stored as YAML), (`Array` or `Hash` or any scalar value stored as JSON) or any custom serializable class. This invokes `ActiveSupport`'s `serialize` macro for that field, passing the serializable class, if given.
Note: when `serialize:` is used, any `default:` should be given in a matching Ruby type--for example, `[]` or `{}` or `{ 'currency' => 'USD' }`--in which case the serializeable class will be used to determine the serialized default value and that will be set as the SQL default.
BTW, here's how `deploybot` changes:
```
-    required_statuses    :string, array: true, limit: 1024, default: nil, null: …
```
=> TECH-4995: support serialize columns

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model/foreign_key_definition.rb, lib/declare_schema/version.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/declare_schema/model/foreign_key_definition_spec.rb
- Fixed a bug where the generated call to add_foreign_key() was not setting `column:`,
so it only worked in cases where Rails could infer the foreign key by convention.
- Added missing spec for `ForeignKeyDeclaration`.
=> no-jira: support foreign key custom column:

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model/column.rb, lib/declare_schema/model/field_spec.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migration_generator.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/field_declaration_dsl_spec.rb, spec/lib/declare_schema/field_spec_spec.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/declare_schema/model/column_spec.rb, spec/lib/generators/declare_schema/migration/migrator_spec.rb
- Use `schema_attributes` for generating both up and down change migrations, so they are guaranteed to be symmetrical.
Note: Rails schema dumper is still used for the down migration to replace a model that has been dropped.
=> TECH-4814: make down migrations inverse of up

CHANGELOG.md, Gemfile.lock, lib/declare_schema/field_declaration_dsl.rb, lib/declare_schema/model.rb, lib/declare_schema/model/column.rb, lib/declare_schema/model/field_spec.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/field_spec_spec.rb
- Exclude unknown options from FieldSpec#sql_options and #schema_attributes.
- Fixed a bug where fk_field_options were getting merged into spec_attrs after checking for equivalence,
leading to phantom migrations with no changes, or missing migrations when just the fk_field_options changed.
=> TECH-4814: fix migration generation

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model/column.rb, lib/declare_schema/model/field_spec.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migration_generator.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/field_spec_spec.rb, spec/lib/declare_schema/model/column_spec.rb
I decided to add this as a rider when I realized we'd been wasting time with the `sql_type` that wasn't significantly different from `type`. I'm guessing it might have been left over from Hobo Fields supporting custom field types like `Email` that were really just a `:string` field with a different validator.
- Removed `sql_type` that was confusing because it was actually the same as `type` (ex: :string) and not
in fact the SQL type (ex: ``varchar(255)'`).
=> TECH-4814: remove sql_type

CHANGELOG.md, Gemfile.lock, README.md, lib/declare_schema.rb, lib/declare_schema/extensions/active_record/fields_declaration.rb, lib/declare_schema/model/field_spec.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/field_spec_spec.rb, spec/lib/declare_schema_spec.rb, spec/lib/generators/declare_schema/migration/migrator_spec.rb
Create configurable defaults for:
- generate foreign key: true
- null: false
- text limit: 0xffff_ffff
- string limit: nil 
- Added configurable default settings for `default_text_limit`, `default_string_limit`, `default_null`,
`default_generate_foreign_keys` and `default_generate_indexing` to allow developers to adhere to project conventions.
- Moved and deprecated default settings for `default_charset` and `default_collation` from `Generators::DeclareSchema::Migration::Migrator` to `::DeclareSchema`
=> Tech 5115 declareschema make foreign key default null text and string limit configurable

.github/workflows/declare_schema_build.yml, CHANGELOG.md, Gemfile.lock, README.md, lib/declare_schema/dsl.rb, lib/declare_schema/extensions/active_record/fields_declaration.rb, lib/declare_schema/model.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/support/model.rb, spec/lib/declare_schema/api_spec.rb, spec/lib/declare_schema/field_declaration_dsl_spec.rb, spec/lib/declare_schema/generator_spec.rb, spec/lib/declare_schema/interactive_primary_key_spec.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/declare_schema/model/column_spec.rb, spec/lib/declare_schema/model/foreign_key_definition_spec.rb, spec/lib/declare_schema/model/index_definition_spec.rb, spec/lib/declare_schema/model/table_options_definition_spec.rb, test_responses.txt
- The `fields` dsl method is being deprecated.
- Added the `declare_schema` method to replace `fields`. We now expect a column's type to come before the name
i.e. `declare schema { string :title }`. Otherwise, there is no difference between `fields` and `declare_schema`.
=> Tech 5112 create declare schema block dsl

CHANGELOG.md, Gemfile.lock, README.md, lib/declare_schema.rb, lib/declare_schema/model.rb, lib/declare_schema/model/column.rb, lib/declare_schema/model/index_definition.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/USAGE, lib/generators/declare_schema/migration/migration_generator.rb, lib/generators/declare_schema/migration/migrator.rb, lib/generators/declare_schema/migration/templates/migration.rb.erb, spec/lib/declare_schema/api_spec.rb, spec/lib/declare_schema/field_spec_spec.rb, spec/lib/declare_schema/generator_spec.rb, spec/lib/declare_schema/interactive_primary_key_spec.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/declare_schema/model/column_spec.rb, spec/lib/declare_schema/model/habtm_model_shim_spec.rb, spec/lib/declare_schema/model/index_definition_spec.rb, spec/spec_helper.rb
- Removed `g|m|c` prompt entirely, since it was confusing. Instead, the migration is always generated; the user may press ^C at the filename prompt to cancel. The migration will be run if `--migrate` is passed; otherwise, the migrate command will be displayed to be run later.
- Added the new configuration option `DeclareSchema.@db_migrate_command =`.
=> no-jira:drop generate and migrate command

lib/declare_schema/model/foreign_key_definition.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/declare_schema/model/foreign_key_definition_spec.rb, spec/lib/declare_schema/model/index_definition_spec.rb
- Fixed bug where foreign key constraint names are not globally unique
Fix failing `rails-4-mysql` [test](https://github.com/Invoca/declare_schema/runs/2153066804?check_suite_focus=true): 
```
Mysql2::Error: Cannot add foreign key constraint: ALTER TABLE `advertisers` ADD CONSTRAINT `index_advertisers_on_category_id`
FOREIGN KEY (`category_id`)
REFERENCES `categories` (`id`)
```
Failure was due to rails 4 [create_table](https://apidock.com/rails/v4.2.1/ActiveRecord/ConnectionAdapters/SchemaStatements/create_table) not recognizing `bigint` type as primary key. With the move to only support rails 5+ we decided to only run this test on rails >= 5
=> Tech 5413 fix bug where constraint is not globally unique

CHANGELOG.md, Gemfile.lock, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migration_generator.rb, lib/generators/declare_schema/migration/templates/migration.rb.erb
- Fixed a bug where up and down in generated migration would be empty in Rails 4.
=> no-jira: fix empty up/down bug

README.md
I noticed the readme was still out of date with the deprecated `fields` DSL
=> Update README to use `declare_schema` instead of `fields`

CHANGELOG.md, Gemfile.lock, lib/declare_schema/extensions/active_record/fields_declaration.rb, lib/declare_schema/model.rb, lib/declare_schema/model/column.rb, lib/declare_schema/model/field_spec.rb, lib/declare_schema/model/habtm_model_shim.rb, lib/declare_schema/model/index_definition.rb, lib/declare_schema/schema_change/column_add.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/api_spec.rb, spec/lib/declare_schema/field_spec_spec.rb, spec/lib/declare_schema/interactive_primary_key_spec.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/declare_schema/model/habtm_model_shim_spec.rb
Note: best to view with `Hide whitespace changes` since there are some indentation changed in tests.
https://ringrevenue.atlassian.net/browse/TECH-5417
Infers foreign key size from the corresponding primary key. In the case of polymorphic keys, this isn't possible, so it always uses `limit: 8` there, unless the schema has already been migrated with `limit: 4`.
```
#
```
=> TECH-5417: infer foreign key limit

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model/field_spec.rb, lib/declare_schema/version.rb, spec/lib/declare_schema/field_spec_spec.rb
- When an `enum` type field is declared, there is now enforcement that its `limit:` must be an array of 1 or more Symbols,
and its `default:`--if given--must be a Symbol or `nil`.
=> no-jira: enforce enum symbols

CHANGELOG.md, Gemfile.lock, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, lib/generators/declare_schema/migration/templates/migration.rb.erb
- Fixed migration file indentation bug in Rails 5 where the first line was indented an extra 4 characters.
And fixed the longstanding triple-spacing bug to use double spacing.
```
class DeclareSchemaMigration1 < (ActiveSupport::VERSION::MAJOR >= 5 ? ActiveRecord::Migration[4.2] : ActiveRecord::Migration)
def self.up
add_column :deploy_targets, :a, :string, limit: 10, null: false, charset: "utf8mb4", collation: "utf8mb4_general_ci"
add_column :deploy_targets, :b, :string, limit: 15, null: false, charset: "utf8mb4", collation: "utf8mb4_general_ci"
end
def self.down
remove_column :deploy_targets, :b
remove_column :deploy_targets, :a
end
end
```
```
class DeclareSchemaMigration1 < (ActiveSupport::VERSION::MAJOR >= 5 ? ActiveRecord::Migration[4.2] : ActiveRecord::Migration)
def self.up …
```
=> TECH-6171: fix indentation and triple spacing

CHANGELOG.md, Gemfile.lock, README.md, lib/declare_schema/model/column.rb, lib/declare_schema/model/table_options_definition.rb, lib/declare_schema/rake.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, lib/generators/declare_schema/migration/templates/migration.rb.erb, spec/lib/declare_schema/migration_generator_spec.rb
I went with a quick and dirty solution here to the problem of generating migrations in a non-Rails application. I have a service, `fish` that is a Sinatra application using ActiveRecord and would like to be able to use declare schema to manage the database schema.
- Added a rake task definition that can be optionally included into a non-Rails project to generate
schema migrations.
=> TECH-8177: add ability to use rake for migration generation for non-rails applications

CHANGELOG.md, Gemfile.lock, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb
- If Rails is defined, raise if `Rails.application` is `nil`.
=> raise if Rails is defined yet Rails.application is nil

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model/foreign_key_definition.rb, lib/declare_schema/model/habtm_model_shim.rb, lib/declare_schema/model/index_definition.rb, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/model/foreign_key_definition_spec.rb, spec/lib/declare_schema/model/habtm_model_shim_spec.rb
When a foreign key is renamed, `declare_schema` creates a migration that includes more than just a column rename. It also includes additions and removals of an index and foreign key. This PR gets rid of everything except the column rename.
=> TECH-5882: renaming a foreign key currently generates incorrect migrations

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model/index_definition.rb, lib/declare_schema/version.rb, spec/lib/declare_schema/model/index_definition_spec.rb
A bug came up when the table name is so long that the short default index name is still too long. To address this, we now fall back to the prefix of the table name, plus up to 4 characters of its sha256. [Slack thread](https://invoca.slack.com/archives/CRGB17J59/p1697040014363769?thread_ts=1697037804.977329&cid=CRGB17J59).
=> issue #154: shorten table name with sha256

CHANGELOG.md, Gemfile.lock, README.md, lib/declare_schema.rb, lib/declare_schema/model/field_spec.rb, lib/declare_schema/model/table_options_definition.rb, lib/declare_schema/version.rb, spec/lib/declare_schema/field_spec_spec.rb, spec/lib/declare_schema/model/table_options_definition_spec.rb, spec/lib/declare_schema_spec.rb, spec/lib/generators/declare_schema/migration/migrator_spec.rb, spec/spec_helper.rb
- Fix a MySQL 8 bug where MySQL 8+ renames charset 'utf8' to 'utf8mb3' and collation 'utf8_general_ci' to
'utf8mb3_general_ci'.
This fix is applied in 3 places:
1. if specified globally in `DeclareSchema.default_charset/default_collation `;
2. if `charset` or `collation` is specified on a table;
3. if `charset` or `collation` is specified on a column
=> TECH-13772: fix MySQL 8 where charset "utf8" is normalized to "utf8mb3" and collation "utf8_..." is normalized to "utf8mb3_..."

lib/declare_schema/model.rb, lib/declare_schema/model/foreign_key_definition.rb, lib/declare_schema/model/habtm_model_shim.rb, lib/declare_schema/model/index_definition.rb, lib/generators/declare_schema/migration/migrator.rb, spec/lib/declare_schema/model/foreign_key_definition_spec.rb, spec/lib/declare_schema/model/habtm_model_shim_spec.rb, spec/lib/declare_schema/model/index_definition_spec.rb
Refactor `HabtmModelShim`:
- move sorting into `initialize`
- omit `connection` and `foreign_key_classes` (replace with `table_names`)
Refactor `IndexSpecification`:
- use explicit keyword args rather than `**options`
- instead of `model`, just pass in `table_name` arg (this makes the `table_name:` keyword arg unnecessary)
- address TODO by changing `fields` to `columns` (but leave alias the other way)
Refactor `ForeignKeyDefinition`:
- use explicit keyword args rather than `**options`
- instead of `model`, just pass in `foreign_key_column`, `constraint_name:`.
=> non-production: move sort into HabtmModelShim#initialize; omit connection and foreign_key_classes

CHANGELOG.md, Gemfile.lock, lib/declare_schema.rb, lib/declare_schema/version.rb, spec/lib/declare_schema_spec.rb
- Make `default_charset=` and `default_collation=` lazy so they don't use the database connection to check the
MySQL version. Instead, that is checked the first time `default_charset` or `default_collation` is called.
=> TECH-13204/make default config lazy

CHANGELOG.md, Gemfile.lock, lib/declare_schema/version.rb, lib/generators/declare_schema/migration/migrator.rb, spec/fixtures/migrations/sqlite3/will_generate_unique_constraint_names_rails_6.txt, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/generators/declare_schema/migration/migrator_spec.rb
I ran into this bug while working  https://invoca.atlassian.net/browse/WEB-7889 . I know I'd seen it before. This time I tracked it down.
- Drop/add index if its settings change (`unique:`, `length:`, etc.)
- Drop indexes before adding, in case any have identical names (so we don't get a SQL exception about the duplicate name)
- Same for foreign key constraints
- Address CVE warning with `bundle update rexml`
=> TECH-16372: drop/add index if settings change (that order is important in case index name is identical)

CHANGELOG.md, Gemfile.lock, lib/declare_schema/model.rb, lib/declare_schema/version.rb, spec/lib/declare_schema/migration_generator_spec.rb
- Fixed bug where a new model with `belongs_to :owner, polymorphic: true` would cause
a "Mysql2::Error: Table '<new table>' doesn't exist:" exception when generating a migration.
=> TECH-16946: fix bug on new model with polymorphic belongs_to

.github/workflows/declare_schema_build.yml, .github/workflows/pipeline.yml, lib/declare_schema/dsl.rb, lib/declare_schema/field_declaration_dsl.rb, spec/lib/declare_schema/migration_generator_spec.rb, spec/lib/declare_schema/model/table_options_definition_spec.rb
- Use the shared github workflow for testing
<sub>This PR was generated using [turbolift](https://github.com/Skyscanner/turbolift).</sub>
=> Add support for Ruby 3.4
